import { signInWithGoogle } from "@/lib/auth";
import { Container, Typography, Button, Box } from "@mui/material";
import Image from "next/image"; // Ensure you have next/image configured for optimized images
import styles from "./LandingPage.module.css"; // Import the CSS module

const LandingPage: React.FC = () => {
  const handleGetStarted = () => {
    signInWithGoogle();
  };

  return (
    <Container maxWidth="lg" className={`${styles.container}`}>
      <Box className={styles.heroSection}>
        <Box className={styles.heroOverlay}>
          <Typography variant="h2" component="h1" className={styles.heroTitle}>
            PANTRY & FRIDGE TRACKER
          </Typography>
          <Typography
            variant="h5"
            component="p"
            className={styles.heroSubtitle}
          >
            Easily manage your pantry & fridge items with revolutionary AI
            Technology.
          </Typography>
          <Button
            variant="contained"
            size="large"
            className={styles.getStartedButton}
            onClick={handleGetStarted}
          >
            Start Tracking
          </Button>
        </Box>
      </Box>

      <Box
        className={`${styles.featuresSection} mt-20 grid grid-cols-1 md:grid-cols-3 gap-8`}
      >
        <Box className={`${styles.feature}`}>
          <Image
            src="/images/easy.jpg"
            alt="Easy to Use"
            width={150}
            height={150}
            className={styles.featureImage}
          />
          <Typography variant="h6" component="h3" className="font-bold mt-4">
            Easy to Use
          </Typography>
          <Typography
            variant="body1"
            component="p"
            className={styles.featureDescription}
          >
            Our user-friendly interface makes managing your pantry a breeze.
          </Typography>
        </Box>
        <Box className={`${styles.feature}`}>
          <Image
            src="/images/recipe.jpg"
            alt="Track Items"
            width={150}
            height={150}
            className={styles.featureImage}
          />
          <Typography variant="h6" component="h3" className="font-bold mt-4">
            Track Items
          </Typography>
          <Typography
            variant="body1"
            component="p"
            className={styles.featureDescription}
          >
            Keep an inventory of all your pantry items with ease.
          </Typography>
        </Box>
        <Box className={`${styles.feature}`}>
          <Image
            src="/images/tracking.jpg"
            alt="Get Notified"
            width={150}
            height={150}
            className={styles.featureImage}
          />
          <Typography variant="h6" component="h3" className="font-bold mt-4">
            Get Great Recipes
          </Typography>
          <Typography
            variant="body1"
            component="p"
            className={styles.featureDescription}
          >
            Get new great recipes generated by AI, considering your items in the
            pantry.
          </Typography>
        </Box>
        <Box className={`${styles.feature}`}>
          <Image
            src="/images/tracking.jpg"
            alt="Get Notified"
            width={150}
            height={150}
            className={styles.featureImage}
          />
          <Typography variant="h6" component="h3" className="font-bold mt-4">
            Get Great Recipes
          </Typography>
          <Typography
            variant="body1"
            component="p"
            className={styles.featureDescription}
          >
            Get new great recipes generated by AI, considering your items in the
            pantry.
          </Typography>
        </Box>
        <Box className={`${styles.feature}`}>
          <Image
            src="/images/tracking.jpg"
            alt="Get Notified"
            width={150}
            height={150}
            className={styles.featureImage}
          />
          <Typography variant="h6" component="h3" className="font-bold mt-4">
            Get Great Recipes
          </Typography>
          <Typography
            variant="body1"
            component="p"
            className={styles.featureDescription}
          >
            Get new great recipes generated by AI, considering your items in the
            pantry.
          </Typography>
        </Box>
        <Box className={`${styles.feature}`}>
          <Image
            src="/images/tracking.jpg"
            alt="Get Notified"
            width={150}
            height={150}
            className={styles.featureImage}
          />
          <Typography variant="h6" component="h3" className="font-bold mt-4">
            Get Great Recipes
          </Typography>
          <Typography
            variant="body1"
            component="p"
            className={styles.featureDescription}
          >
            Get new great recipes generated by AI, considering your items in the
            pantry.
          </Typography>
        </Box>
      </Box>
    </Container>
  );
};

export default LandingPage;
