import { signInWithGoogle } from "@/lib/auth";
import { Container, Typography, Button, Box } from "@mui/material";
import Image from "next/image"; // Ensure you have next/image configured for optimized images

const LandingPage: React.FC = () => {
  const handleGetStarted = () => {
    signInWithGoogle();
  };

  return (
    <Container maxWidth="lg" className="py-20">
      <Box
        className="text-center"
        sx={{
          backgroundImage: 'url("/images/bg.jpg")', // Add a background image
          backgroundSize: "cover",
          backgroundPosition: "center",
          color: "#fff", // Make text white for better contrast
          py: 10, // Add vertical padding
          borderRadius: 3, // Add rounded corners for a modern look
        }}
      >
        <Typography
          variant="h2"
          component="h1"
          sx={{
            fontWeight: "bold",
            mb: 4,
            fontSize: { xs: "2.5rem", md: "3.5rem" }, // Responsive font size
            textShadow: "2px 2px 10px rgba(0,0,0,0.5)", // Add subtle text shadow
          }}
        >
          Pantry & Fridge Tracker App
        </Typography>
        <Typography
          variant="h5"
          component="p"
          sx={{
            mb: 6,
            fontSize: { xs: "1.2rem", md: "1.5rem" },
            textShadow: "1px 1px 5px rgba(0,0,0,0.5)",
          }}
        >
          Easily manage your pantry items and keep track of what you have.
        </Typography>
        <Button
          variant="contained"
          color="secondary"
          size="large"
          sx={{
            px: 5, // Add horizontal padding
            py: 1.5, // Add vertical padding
            fontSize: "1.2rem", // Increase button text size
            textTransform: "none", // Remove uppercase transformation
            borderRadius: "25px", // Rounded button
            boxShadow: "0px 4px 15px rgba(0, 0, 0, 0.2)", // Add button shadow
          }}
          onClick={handleGetStarted}
        >
          Get Started
        </Button>
      </Box>

      <Box
        className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8"
        sx={{ mt: 10 }}
      >
        <Box className="text-center">
          <Image
            src="/images/easy.jpg"
            alt="Easy to Use"
            width={150}
            height={150}
          />
          <Typography
            variant="h6"
            component="h3"
            className="font-bold mt-4"
            sx={{ mt: 4 }}
          >
            Easy to Use
          </Typography>
          <Typography variant="body1" component="p" sx={{ mt: 2 }}>
            Our user-friendly interface makes managing your pantry a breeze.
          </Typography>
        </Box>
        <Box className="text-center">
          <Image
            src="/images/recipe.jpg"
            alt="Track Items"
            width={150}
            height={150}
          />
          <Typography
            variant="h6"
            component="h3"
            className="font-bold mt-4"
            sx={{ mt: 4 }}
          >
            Track Items
          </Typography>
          <Typography variant="body1" component="p" sx={{ mt: 2 }}>
            Keep an inventory of all your pantry items with ease.
          </Typography>
        </Box>
        <Box className="text-center">
          <Image
            src="/images/tracking.jpg"
            alt="Get Notified"
            width={150}
            height={150}
          />
          <Typography
            variant="h6"
            component="h3"
            className="font-bold mt-4"
            sx={{ mt: 4 }}
          >
            Get Great Recipes
          </Typography>
          <Typography variant="body1" component="p" sx={{ mt: 2 }}>
            Get new great recipes generated by AI, considering your items in the
            pantry.
          </Typography>
        </Box>
      </Box>
    </Container>
  );
};

export default LandingPage;
